name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ticket-booking
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run lint
      run: npm run lint
      continue-on-error: false
    
    - name: Build project
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Run tests
      run: npm test
      env:
        CI: true
    
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: production-build
        path: |
          ./dist
          ./dist/assets